[package]
name = "memchunk"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
abstractions = { path = "../../crates/abstractions" }
alloc-madvise = { version = "0.3.0", default-features = false }
rayon = "1.6.1"
transpose = "0.2.2"
unroll = "0.1.5"
