[package]
name = "opencl-experiments"
version = "0.1.0"
edition = "2021"

[[example]]
name = "trivial"
path = "examples/trivial.rs"

[dependencies]
ocl = "0.19.3"
ocl-stream = "0.3.5"
rand = "0.8.4"

[dev-dependencies]
approx = "0.5.1"
