[package]
name = "vecdb"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
abstractions = { path = "../../crates/abstractions" }
fmmap = { version = "0.3.2", features = ["tokio", "tokio-async"] }
futures = "0.3.25"
tokio = { version = "1.24.2", features = ["full"] }
