[package]
name = "vecdb"
version = "0.1.0"
edition = "2021"

[dependencies]
fmmap = { version = "0.3.2", features = ["tokio", "tokio-async"] }
futures = "0.3.25"
tokio = { version = "1.23.1", features = ["full"] }
